window.LITBUY_PRODUCTS = [
  {
    id: 1,
    name: "Balenciaga Beige BALEN CIAGA Hoodie",
    category: "hoodies",
    badge: "hot",
    price: 196,
    brand: "Balenciaga",
    image: "https://cdn.maisonlooks.com/products/file-1778310149772-24668939.webp",
    desc: "Discover the Balenciaga Beige BALEN CIAGA Hoodie, featuring an oversized fit and bold graphic print. Crafted from premium cotton, this luxury streetwear piece is ideal for casual, everyday style.",
    url: "https://streetstyle.maisonlooks.com/en/p/balenciaga-beige-hoodie-with-balen-ciaga-print-9ff998?returnTo=%2F",
  },
  {
    id: 2,
    name: "Stone Island Grey Half-Zip Sweater",
    category: "hoodies",
    badge: "trending",
    brand: "Stone Island",
    image: "https://cdn.maisonlooks.com/products/file-1778421537762-48980604.webp",
    desc: "Discover the timeless appeal of the Stone Island 68-15 half-zip sweater in soft heather grey with a quarter-zip design and signature Stone Island badge.",
    url: "https://streetstyle.maisonlooks.com/en/p/stone-island-68-15-grey-half-zip-sweater-b0c932?returnTo=%2F",
  },
  {
    id: 3,
    name: "Stone Island 68-15 Black Puffer Jacket",
    category: "jackets",
    badge: "hot",
    brand: "Stone Island",
    image: "https://cdn.maisonlooks.com/products/file-1778426506271-270780858.webp",
    desc: "Stay warm and stylish in the Stone Island 68-15 Black Hooded Puffer Jacket with a water-resistant nylon shell, chevron quilting, and adjustable hood.",
    url: "https://streetstyle.maisonlooks.com/en/p/stone-island-68-15-black-hooded-puffer-jacket-1eed77?returnTo=%2F",
  },
  {
    id: 4,
    name: "Dior Lime Green Sneakers - Dior Book Tote",
    category: "shoes",
    badge: "hot",
    brand: "Dior",
    image: "https://cdn.maisonlooks.com/products/file-1778498836301-705351020.webp",
    desc: "Discover the Dior Dior Book Tote sneakers in striking lime green, combining comfort and style for everyday wear and special occasions.",
    url: "https://streetstyle.maisonlooks.com/en/p/dior-dior-book-tote-lime-green-sneakers-43dac4?returnTo=%2F",
  },
  {
    id: 5,
    name: "Nike Air Jordan 4 Super Mario Sneakers",
    category: "shoes",
    badge: "trending",
    brand: "Nike",
    image: "https://cdn.maisonlooks.com/products/file-1778500935232-699864393.webp",
    desc: "Step into iconic style with the Nike Air Jordan 4 Super Mario sneakers in a black and green color scheme with premium suede and mesh.",
    url: "https://streetstyle.maisonlooks.com/en/p/nike-air-jordan-4-super-mario-black-green-sneakers-61ae7a?returnTo=%2F",
  },
  {
    id: 6,
    name: "Apple AirPods Max (Plastic) Black",
    category: "electronics",
    badge: "hot",
    brand: "Apple",
    image: "https://cdn.maisonlooks.com/products/file-1778312334863-514077315.webp",
    desc: "Experience premium sound with the Apple AirPods Max (Plastic) in sleek black, designed for comfort, style, noise cancellation, and clear audio.",
    url: "https://streetstyle.maisonlooks.com/en/p/apple-airpods-max-plastic-black-headphones-32047b?returnTo=%2F",
  },
  {
    id: 7,
    name: "Chanel Black Lambskin Wallet",
    category: "accessories",
    badge: "trending",
    brand: "Chanel",
    image: "https://cdn.maisonlooks.com/products/file-1778309942994-471991429.webp",
    desc: "Discover the timeless elegance of this Chanel Classic Flap wallet in sleek black lambskin with a quilted design and gold CC logo.",
    url: "https://streetstyle.maisonlooks.com/en/p/chanel-classic-flap-black-lambskin-wallet-08e7c5?returnTo=%2F",
  },
  {
    id: 8,
    name: "Pink & White Panel Track Pants - Unisex",
    category: "pants",
    badge: "hot",
    brand: "MaisonLooks",
    image: "https://cdn.maisonlooks.com/products/file-1778500330675-514242586.webp",
    desc: "Discover these unisex track pants featuring a pink body with white and grey side panels, a relaxed fit, elastic waistband, and drawstring.",
    url: "https://streetstyle.maisonlooks.com/en/p/pink-white-panel-track-pants-71d579?returnTo=%2F",
  },
  {
    id: 9,
    name: "Stussy Navy T-Shirt 'Infiltrate'",
    category: "t-shirts",
    badge: "hot",
    brand: "Stussy",
    image: "https://cdn.maisonlooks.com/products/file-1778670350049-827671661.webp",
    desc: "Discover the Stussy Infiltrate Navy T-Shirt, featuring a graphic design with Stussy logo artwork and comfortable cotton construction.",
    url: "https://streetstyle.maisonlooks.com/en/p/stussy-st-ssy-infiltrate-navy-t-shirt-31b46f?returnTo=%2Fc%2Ft-shirts",
  },
  {
    id: 10,
    name: "CP Company Goggle Black Beanie",
    category: "headwear",
    badge: "trending",
    brand: "CP Company",
    image: "https://cdn.maisonlooks.com/products/file-1778413475968-394198426.webp",
    desc: "Stay warm and stylish with the CP Company Goggle Black Beanie, a unisex accessory with a bold goggle design and reflective lenses.",
    url: "https://streetstyle.maisonlooks.com/en/p/cp-company-goggle-black-beanie-730c72?returnTo=%2Fc%2Fheadwear",
  },
  {
    id: 11,
    name: "Dior Sauvage EDP Concentrated - Fragrance",
    category: "other",
    badge: "hot",
    brand: "Dior",
    image: "https://cdn.maisonlooks.com/products/file-1778503302651-351683525.webp",
    desc: "Discover Dior Sauvage Eau de Parfum Concentrated, a sophisticated fragrance with citrus, spice, and wood notes.",
    url: "https://streetstyle.maisonlooks.com/en/p/dior-sauvage-eau-de-parfum-concentrated-24f9ac?returnTo=%2Fc%2Fperfume",
  },
  {
    id: 12,
    name: "Light Grey Hoodie with Yacht Print",
    category: "hoodies",
    badge: "trending",
    brand: "MaisonLooks",
    image: "https://cdn.maisonlooks.com/products/file-1778418402290-288116222.webp",
    desc: "Stay cozy and stylish with this light grey hoodie featuring a yacht graphic design, soft cotton construction, and a relaxed fit.",
    url: "https://streetstyle.maisonlooks.com/en/p/hoodie-with-yacht-graphic-in-light-grey-ea1d27?returnTo=%2Fsearch%3Fq%3Dhoodie",
  },
  {
    id: 13,
    name: "USA White Soccer Jersey with Red/Blue Trim",
    category: "jersey",
    badge: "hot",
    brand: "USA",
    image: "https://cdn.maisonlooks.com/products/file-1778596007870-994274975.webp",
    desc: "Show your support with this white USA soccer jersey featuring red and blue trim accents and breathable polyester construction.",
    url: "https://streetstyle.maisonlooks.com/en/p/usa-jersey-white-red-blue-trim-soccer-top-e17c02?returnTo=%2Fsearch%3Fq%3Djersey",
  },
  {
    id: 14,
    name: "Louis Vuitton Tabi Checkered Scarf - Black/Grey",
    category: "accessories",
    badge: "trending",
    brand: "Louis Vuitton",
    image: "https://cdn.maisonlooks.com/products/file-1778600414096-708452940.webp",
    desc: "Discover the Louis Vuitton Tabi scarf in a black and grey checkered design, a versatile accessory for autumn and winter styling.",
    url: "https://streetstyle.maisonlooks.com/en/p/louis-vuitton-tabi-black-grey-checkered-scarf-076847?returnTo=%2Fc%2Faccessories",
  },
  {
    id: 15,
    name: "Nike Air Force 1 White/Brown Sneakers",
    category: "shoes",
    badge: "trending",
    brand: "Nike",
    image: "https://cdn.maisonlooks.com/products/file-1778646154333-594085514.webp",
    desc: "Discover the Nike Air Force 1 in a white and brown colorway with leather construction, brown detailing, and the signature Nike swoosh.",
    url: "https://streetstyle.maisonlooks.com/en/p/nike-air-force-1-white-brown-sneakers-bca374?returnTo=%2Fc%2Fshoes",
  },
  {
    id: 16,
    name: "Nike Air Max Tn Rainbow Sneakers",
    category: "shoes",
    badge: "hot",
    brand: "Nike",
    image: "https://cdn.maisonlooks.com/products/file-1778653145828-851515538.webp",
    desc: "Discover the Nike Air Max Tn Rainbow Green sneakers with a rainbow wave design, neon green details, and synthetic materials.",
    url: "https://streetstyle.maisonlooks.com/en/p/nike-air-max-tn-rainbow-green-sneakers-49f5de?returnTo=%2Fc%2Fshoes",
  },
  {
    id: 17,
    name: "Moncler Maya Letter Blue Parka",
    category: "jackets",
    badge: "trending",
    brand: "Moncler",
    image: "https://cdn.maisonlooks.com/products/file-1778498098816-994681760.webp",
    desc: "Discover the Moncler Maya Letter Blue Parka, a warm winter essential with a bold colorway and signature Moncler detailing.",
    url: "https://streetstyle.maisonlooks.com/en/p/moncler-maya-letter-blue-parka-e205d7?returnTo=%2F",
  },
  {
    id: 18,
    name: "Trapstar Black Track Pants - Shooters Style",
    category: "pants",
    badge: "trending",
    brand: "Trapstar",
    image: "https://cdn.maisonlooks.com/products/file-1778650423638-945216069.webp",
    desc: "Shop the Trapstar Black Shooters Track Pants featuring a relaxed fit, white drawstrings, and orange branding.",
    url: "https://streetstyle.maisonlooks.com/en/p/trapstar-black-shooters-track-pants-696ebe?returnTo=%2F",
  },
  {
    id: 19,
    name: "Polo Ralph Lauren Navy Red Hoodie",
    category: "hoodies",
    badge: "trending",
    brand: "Polo Ralph Lauren",
    image: "https://cdn.maisonlooks.com/products/file-1778671299906-371009841.webp",
    desc: "Shop the Polo Ralph Lauren Big Pony hoodie in navy with red accents, a classic zip-up shape, and relaxed everyday fit.",
    url: "https://streetstyle.maisonlooks.com/en/p/polo-ralph-lauren-big-pony-hoodie-navy-red-4bf2e6?returnTo=%2F",
  },
  {
    id: 20,
    name: "Goyard Goyardine Grey Tote Bag",
    category: "bags",
    badge: "hot",
    brand: "Goyard",
    image: "https://cdn.maisonlooks.com/products/file-1778677629880-113160913.webp",
    desc: "Discover the Goyard Goyardine tote bag in grey, made from durable Goyardine canvas with a distinctive geometric print.",
    url: "https://streetstyle.maisonlooks.com/en/p/goyard-goyardine-grey-tote-bag-97d84b?returnTo=%2Fc%2Faccessories",
  },
  {
    id: 21,
    name: "Apple AirPods (2nd Gen) White",
    category: "electronics",
    badge: "trending",
    brand: "Apple",
    image: "https://cdn.maisonlooks.com/products/file-1778672533933-911036540.webp",
    desc: "Experience seamless audio with Apple AirPods (2nd Gen) in classic white, with wireless pairing, sound quality, and a compact charging case.",
    url: "https://streetstyle.maisonlooks.com/en/p/apple-airpods-2nd-gen-white-earbuds-acddfc?returnTo=%2Fsearch%3Fq%3Delectronics",
  },
  {
    id: 22,
    name: "Lancome Miracle Perfume - 100ml",
    category: "other",
    badge: "trending",
    brand: "Lancome",
    image: "https://cdn.maisonlooks.com/products/file-1778629479755-52930248.webp",
    desc: "Discover Lancome Miracle L'Eau de Parfum, a 100ml bottle with a floral scent for day and evening wear.",
    url: "https://streetstyle.maisonlooks.com/en/p/lanc-me-miracle-l-eau-de-parfum-100ml-0460d8?returnTo=%2Fc%2Fperfume",
  },
  {
    id: 23,
    name: "Adidas Arsenal Black Football Jersey",
    category: "jersey",
    badge: "trending",
    brand: "Adidas",
    image: "https://cdn.maisonlooks.com/products/file-1778418618964-331088831.webp",
    desc: "Shop the Adidas Arsenal black classic football jersey featuring the club crest, Emirates sponsorship, and Aeroready technology.",
    url: "https://streetstyle.maisonlooks.com/en/p/adidas-arsenal-black-classic-football-jersey-a9ef97?returnTo=%2Fsearch%3Fq%3Djersey",
  },
  {
    id: 24,
    name: "Corteiz CRTZ Black T-Shirt with Safety Pin Design",
    category: "t-shirts",
    badge: "trending",
    brand: "Corteiz",
    image: "https://cdn.maisonlooks.com/products/file-1778648748380-632287860.webp",
    desc: "Discover the Corteiz CRTZ black t-shirt, featuring a metallic safety pin graphic, cotton construction, and a regular printed fit.",
    url: "https://streetstyle.maisonlooks.com/en/p/corteiz-crtz-black-safety-pin-t-shirt-e437a3?returnTo=%2Fc%2Ft-shirts",
  },
];

window.LITBUY_CATEGORIES = [
  { slug: "shoes", name: "Shoes", icon: "SH", url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/shoes", hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/shoes", trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/shoes" },
  { slug: "hoodies", name: "Hoodies / Sweaters", icon: "HD", url: "https://streetstyle.maisonlooks.com/en/search?q=hoodie", hotUrl: "https://streetstyle.maisonlooks.com/en/search?q=hoodie", trendingUrl: "https://streetstyle.maisonlooks.com/en/search?q=sweater" },
  { slug: "t-shirts", name: "T-Shirts", icon: "TS", url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/t-shirts", hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/t-shirts", trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/t-shirts" },
  { slug: "jackets", name: "Jackets", icon: "JK", url: "https://streetstyle.maisonlooks.com/en/search?q=jacket", hotUrl: "https://streetstyle.maisonlooks.com/en/search?q=puffer", trendingUrl: "https://streetstyle.maisonlooks.com/en/search?q=parka" },
  { slug: "pants", name: "Pants / Shorts", icon: "PT", url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bottoms", hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bottoms", trendingUrl: "https://streetstyle.maisonlooks.com/en/search?q=pants" },
  { slug: "bags", name: "Bags", icon: "BG", url: "https://streetstyle.maisonlooks.com/en/search?q=bag", hotUrl: "https://streetstyle.maisonlooks.com/en/search?q=tote", trendingUrl: "https://streetstyle.maisonlooks.com/en/search?q=bag" },
  { slug: "headwear", name: "Headwear", icon: "HW", url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/headwear", hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/headwear", trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/headwear" },
  { slug: "accessories", name: "Accessories", icon: "AC", url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/accessories", hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/accessories", trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/accessories" },
  { slug: "jersey", name: "Jersey", icon: "JR", url: "https://streetstyle.maisonlooks.com/en/search?q=jersey", hotUrl: "https://streetstyle.maisonlooks.com/en/search?q=jersey", trendingUrl: "https://streetstyle.maisonlooks.com/en/search?q=football%20jersey" },
  { slug: "electronics", name: "Electronics", icon: "EL", url: "https://streetstyle.maisonlooks.com/en/search?q=electronics", hotUrl: "https://streetstyle.maisonlooks.com/en/search?q=airpods", trendingUrl: "https://streetstyle.maisonlooks.com/en/search?q=electronics" },
  { slug: "other", name: "Other Stuff", icon: "OT", url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/perfume", hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/perfume", trendingUrl: "https://streetstyle.maisonlooks.com/en/search?q=fragrance" },
];

window.LITBUY_BRANDS = [
  "Balenciaga", "Stone Island", "Dior", "Nike", "Apple", "Chanel", "Stussy", "CP Company", "Louis Vuitton", "Moncler", "Trapstar", "Polo Ralph Lauren", "Goyard", "Adidas", "Corteiz",
];

window.LITBUY_KEYWORDS = [
  "Balenciaga Hoodie", "Stone Island Sweater", "Air Jordan 4", "Air Force 1", "Air Max TN", "Stussy T-Shirt", "CP Company Beanie", "Dior Sauvage", "Arsenal Jersey", "AirPods",
];

window.LITBUY_SEO_ROUTES = [
  { label: "LitBuy Finds", href: "finds.html" },
  { label: "LitBuy Spreadsheet", href: "spreadsheet.html" },
  { label: "LitBuy Review", href: "review.html" },
  { label: "LitBuy QC Photos", href: "qc.html" },
  { label: "LitBuy Blog", href: "blog.html" },
  { label: "LitBuy New", href: "new.html" },
  { label: "LitBuy Help", href: "help.html" },
  { label: "LitBuy Haul", href: "haul.html" },
  { label: "LitBuy Alternatives", href: "alternatives.html" },
  { label: "LitBuy Shopping Agent", href: "about.html" },
];
