window.LITBUY_PRODUCTS = [
  {
    id: 1,
    name: "Nike Air Jordan 3 Sail/University Blue Sneakers",
    category: "shoes",
    badge: "hot",
    price: 68,
    brand: "Nike",
    image: "images/products/nike-air-jordan-3-sail-university-blue-sneakers-833aa8.webp",
    desc: "Nike Air Jordan 3 sneakers in Sail and University Blue with classic elephant-print details and a high-top profile.",
    url: "https://streetstyle.maisonlooks.com/en/p/nike-air-jordan-3-sail-university-blue-sneakers-833aa8?returnTo=%2Fsearch%3Fq%3Dnike",
  },
  {
    id: 2,
    name: "Nike Air Jordan 3 White/University Red Sneakers",
    category: "shoes",
    badge: "trending",
    price: 55,
    brand: "Nike",
    image: "images/products/nike-air-jordan-3-white-university-red-sneakers-92ad36.webp",
    desc: "White and University Red Air Jordan 3 sneakers with a timeless basketball silhouette for everyday styling.",
    url: "https://streetstyle.maisonlooks.com/en/p/nike-air-jordan-3-white-university-red-sneakers-92ad36?returnTo=%2Fsearch%3Fq%3Dnike",
  },
  {
    id: 3,
    name: "Moncler Black Logo Sweatshirt with Fire Cap",
    category: "t-shirts",
    badge: "hot",
    price: 42,
    brand: "Moncler",
    image: "images/products/moncler-logo-crewneck-sweatshirt-single-black-with-fire-cap-c4a5c2.webp",
    desc: "Black Moncler crewneck sweatshirt with a bold logo graphic and fire-cap detail for casual streetwear looks.",
    url: "https://streetstyle.maisonlooks.com/en/p/moncler-logo-crewneck-sweatshirt-single-black-with-fire-cap-c4a5c2?returnTo=%2Fsearch%3Fq%3DT%25E6%2581%25A4",
  },
  {
    id: 4,
    name: "Moncler White Logo Crewneck Sweatshirt",
    category: "t-shirts",
    badge: "trending",
    price: 38,
    brand: "Moncler",
    image: "images/products/moncler-single-white-logo-crewneck-sweatshirt-1b4c9e.webp",
    desc: "White Moncler crewneck sweatshirt with a clean logo design, made for relaxed layering and daily outfits.",
    url: "https://streetstyle.maisonlooks.com/en/p/moncler-single-white-logo-crewneck-sweatshirt-1b4c9e?returnTo=%2Fsearch%3Fq%3DT%25E6%2581%25A4",
  },
  {
    id: 5,
    name: "Moncler Black Puffer Jacket",
    category: "jackets",
    badge: "hot",
    price: 120,
    brand: "Moncler",
    image: "images/products/moncler-nfc-93f7de.webp",
    desc: "Black Moncler puffer jacket with a quilted body and lightweight cold-weather styling.",
    url: "https://streetstyle.maisonlooks.com/en/p/moncler-nfc-93f7de?returnTo=%2Fsearch%3Fq%3D%25E5%25A4%25B9%25E5%2585%258B",
  },
  {
    id: 6,
    name: "Unisex Dark Gray Zip Hoodie Jacket",
    category: "jackets",
    badge: "trending",
    price: 65,
    brand: "MaisonLooks",
    image: "images/products/unisex-e54346.webp",
    desc: "Unisex dark gray zip hoodie jacket with a relaxed fit for casual outfits and light layering.",
    url: "https://streetstyle.maisonlooks.com/en/p/unisex-e54346?returnTo=%2Fsearch%3Fq%3D%25E5%25A4%25B9%25E5%2585%258B",
  },
  { id: 7, name: "Jordan 1 Retro High OG", category: "shoes", styles: 12, price: 45, brand: "Nike" },
  { id: 8, name: "Dunk Low Panda", category: "shoes", styles: 8, price: 38, brand: "Nike" },
  { id: 9, name: "Chrome Hearts Cross Tee", category: "t-shirts", price: 28, brand: "Chrome Hearts" },
  { id: 10, name: "Stussy Basic Hoodie", category: "hoodies", price: 32, brand: "Stussy" },
  { id: 11, name: "Essentials Oversized Hoodie", category: "hoodies", price: 28, brand: "Essentials" },
  { id: 12, name: "Denim Tears Cotton Wreath Hoodie", category: "hoodies", price: 48, brand: "Denim Tears" },
  { id: 13, name: "Amiri MX1 Distressed Jeans", category: "pants", price: 72, brand: "Amiri" },
  { id: 14, name: "North Face 700 Puffer Jacket", category: "jackets", price: 55, brand: "North Face" },
  { id: 15, name: "Goyard St. Louis Tote PM", category: "bags", price: 48, brand: "Goyard" },
  { id: 16, name: "Supreme Box Logo Cap", category: "headwear", price: 18, brand: "Supreme" },
  { id: 17, name: "Dive-Style Stainless Watch", category: "accessories", price: 45, brand: "Accessories" },
  { id: 18, name: "Real Madrid Home Jersey 24/25", category: "jersey", price: 22, brand: "Real Madrid" },
  { id: 19, name: "Wireless Earbuds Case Set", category: "electronics", price: 25, brand: "Audio" },
  { id: 20, name: "Creed Aventus Perfume", category: "other", price: 28, brand: "Creed" },
  { id: 21, name: "Travis Scott x Jordan 4", category: "shoes", badge: "hot", price: 58, brand: "Nike" },
  { id: 22, name: "Stone Island Crewneck Sweater", category: "hoodies", price: 42, brand: "Stone Island" },
  { id: 23, name: "New Balance 550", category: "shoes", price: 35, brand: "New Balance" },
  { id: 24, name: "CP Company Goggle Jacket", category: "jackets", price: 68, brand: "CP Company" },
];

window.LITBUY_CATEGORIES = [
  {
    slug: "shoes",
    name: "Shoes",
    icon: "👟",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/shoes",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/shoes",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/sneakers",
  },
  {
    slug: "hoodies",
    name: "Hoodies / Sweaters",
    icon: "🧥",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/clothing",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/clothing",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/clothing",
  },
  {
    slug: "t-shirts",
    name: "T-Shirts",
    icon: "👕",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/t-shirts",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/t-shirts",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/t-shirts",
  },
  {
    slug: "jackets",
    name: "Jackets",
    icon: "🧥",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/jackets",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/jackets",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/outerwear",
  },
  {
    slug: "pants",
    name: "Pants / Shorts",
    icon: "👖",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bottoms",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bottoms",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bottoms",
  },
  {
    slug: "bags",
    name: "Bags",
    icon: "👜",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bags",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bags",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/bags",
  },
  {
    slug: "headwear",
    name: "Headwear",
    icon: "🧢",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/headwear",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/headwear",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/headwear",
  },
  {
    slug: "accessories",
    name: "Accessories",
    icon: "⌚",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/accessories",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/accessories",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/accessories",
  },
  {
    slug: "jersey",
    name: "Jersey",
    icon: "⚽",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/clothing",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/clothing",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/clothing",
  },
  {
    slug: "electronics",
    name: "Electronics",
    icon: "📱",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/electronics",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/electronics",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/electronics",
  },
  {
    slug: "other",
    name: "Other Stuff",
    icon: "✨",
    url: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/perfume",
    hotUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/perfume",
    trendingUrl: "https://streetstyle.maisonlooks.com/en/s/StreetStyle/c/perfume",
  },
];

window.LITBUY_BRANDS = [
  "Chrome Hearts", "Nike", "Adidas", "Stussy", "Essentials", "Denim Tears", "Amiri",
];

window.LITBUY_KEYWORDS = [
  "AJ1", "AJ3", "AJ4", "Jordan 4", "Chrome Hearts", "Stussy", "Essentials", "Denim Tears", "Amiri", "Nike", "New Balance",
];

window.LITBUY_SEO_ROUTES = [
  { label: "LitBuy Finds", href: "finds.html" },
  { label: "LitBuy Spreadsheet", href: "spreadsheet.html" },
  { label: "LitBuy Review", href: "review.html" },
  { label: "LitBuy Help", href: "help.html" },
  { label: "LitBuy Haul", href: "haul.html" },
  { label: "LitBuy Alternatives", href: "alternatives.html" },
  { label: "LitBuy Shopping Agent", href: "about.html" },
];
